# .streamlit/config.toml
[server]
headless = true
enableCORS = false
port = 8501

[theme]
base = "dark"
primaryColor = "#7C3AED"            # fresh violet
backgroundColor = "#0B1020"         # deep navy
secondaryBackgroundColor = "#121834" # card background
textColor = "#E6E8EE"               # soft white
font = "sans serif"
